# Generated by Django 5.1.5 on 2025-03-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_aitool_options_aitool_created_at_and_more'),
        ('users', '0002_alter_customuser_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favoritos',
            field=models.ManyToManyField(blank=True, default=None, help_text='User Favorite AIs', related_name='favorited_by', to='catalog.aitool'),
        ),
    ]
