# Generated by Django 5.1.5 on 2025-03-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_aitool_options_aitool_created_at_and_more'),
        ('users', '0003_alter_customuser_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text="User's favorite AI tools", related_name='favorited_by', to='catalog.aitool'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='User email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='User first name', max_length=255),
        ),
    ]
