# Generated by Django 5.1.6 on 2025-03-10 15:54

from django.db import migrations
from django.db.models import F


def migrate_user_favorites(apps, schema_editor):
    """
    Move data from catalog.UserFavorite to interaction.UserFavorite
    """
    # We can't import the models directly as they may be a newer version
    # than this migration expects. We use the historical version.
    try:
        # Try to get the old model (it might not exist if this migration runs after the model is deleted)
        CatalogUserFavorite = apps.get_model('catalog', 'UserFavorite')
        InteractionUserFavorite = apps.get_model('interaction', 'UserFavorite')
        
        # Copy all records from the old model to the new one
        for old_favorite in CatalogUserFavorite.objects.all():
            InteractionUserFavorite.objects.create(
                user_id=old_favorite.user_id,
                ai_tool_id=old_favorite.ai_tool_id,
                created_at=old_favorite.created_at
            )
        
        print(f"Successfully migrated {CatalogUserFavorite.objects.count()} user favorites from catalog to interaction app.")
    except LookupError:
        # If the old model doesn't exist anymore, just skip
        print("Catalog UserFavorite model not found. Skipping data migration.")


def reverse_migrate_user_favorites(apps, schema_editor):
    """
    Move data back from interaction.UserFavorite to catalog.UserFavorite
    This is only for rollback purposes and might not work if the catalog model is already deleted.
    """
    try:
        CatalogUserFavorite = apps.get_model('catalog', 'UserFavorite')
        InteractionUserFavorite = apps.get_model('interaction', 'UserFavorite')
        
        # Copy all records from the new model to the old one
        for new_favorite in InteractionUserFavorite.objects.all():
            CatalogUserFavorite.objects.create(
                user_id=new_favorite.user_id,
                ai_tool_id=new_favorite.ai_tool_id,
                created_at=new_favorite.created_at
            )
        
        print(f"Successfully migrated {InteractionUserFavorite.objects.count()} user favorites from interaction to catalog app.")
    except LookupError:
        print("Catalog UserFavorite model not found. Cannot reverse migrate data.")


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_userfavorite'),
        ('catalog', '0005_delete_userfavorite'),
    ]

    operations = [
        migrations.RunPython(migrate_user_favorites, reverse_migrate_user_favorites),
    ]
