# Generated by Django 5.1.7 on 2025-03-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_migrate_userfavorites_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
