# Generated by Django 5.1.7 on 2025-03-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_userfavorite'),
        ('interaction', '0004_delete_userfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteprompt',
            name='ai_tool',
        ),
        migrations.AddField(
            model_name='favoriteprompt',
            name='ai_tools',
            field=models.ManyToManyField(blank=True, help_text='AI tools this prompt can be used with', related_name='favorite_prompts', to='catalog.aitool'),
        ),
    ]
