# Generated by Django 5.1.7 on 2025-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_remove_favoriteprompt_ai_tool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedchat',
            old_name='shared_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='sharedchat',
            old_name='shared_with',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='sharedchat',
            name='expiration_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days until the shared chat expires'),
        ),
    ]
