# Generated by Django 5.1.5 on 2025-02-13 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('endpoint', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('popularity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_images/')),
            ],
        ),
    ]
