# Generated by Django 5.1.6 on 2025-03-13 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AITool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("endpoint", models.URLField()),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="ai_images/"),
                ),
                ("popularity", models.FloatField(default=0)),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI API"),
                            ("huggingface", "Hugging Face API"),
                            ("custom", "Custom Integration"),
                            ("none", "No Integration"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                ("api_model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "api_endpoint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="catalog.aitool",
                    ),
                ),
            ],
        ),
    ]
