# Generated by Django 5.1.6 on 2025-02-27 05:43

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitool',
            options={'ordering': ['-popularity', 'name'], 'verbose_name': 'AI Tool', 'verbose_name_plural': 'AI Tools'},
        ),
        migrations.AddField(
            model_name='aitool',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when this record was created'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='category',
            field=models.CharField(choices=[('Transcription', 'Transcription'), ('Image Generator', 'Image Generator'), ('Word Processor', 'Word Processor'), ('Other', 'Other')], db_index=True, default='Other', help_text='Category of the AI tool', max_length=100),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='description',
            field=models.TextField(help_text='Detailed description of the AI tool'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='endpoint',
            field=models.URLField(help_text='URL of the AI service', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the AI tool', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing the AI tool', null=True, upload_to='ai_images/'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the AI tool', max_length=255),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='popularity',
            field=models.IntegerField(help_text='Popularity rating from 0 to 100', validators=[django.core.validators.MinValueValidator(0, message='Popularity must be at least 0'), django.core.validators.MaxValueValidator(100, message='Popularity cannot exceed 100')]),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='provider',
            field=models.CharField(db_index=True, help_text='Provider or company that created the AI tool', max_length=255),
        ),
    ]
